#pragma once

#include <Core/Export.h>

#ifdef MAHO_DRAWTRIANGLEFEATURE_MODULE_EXPORTS
#	define MAHO_DRAWTRIANGLEFEATURE_API MAHO_EXPORT
#else
#	define MAHO_DRAWTRIANGLEFEATURE_API MAHO_IMPORT
#endif
