// Generated by Tools/scan_deps.py — DO NOT EDIT.
// Dependency macros per (Class, Key). Use:
//   using FDepends = TTypeList<FDefaultSlot, TTypeList<MAHO_DEPS_Class_Key>>;
#pragma once
#define MAHO_DEPS_FWorld_FDefaultSlot FAI
